// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherLogger.Infrastructure.Persistence;

#nullable disable

namespace WeatherLogger.Infrastructure.Migrations
{
    [DbContext(typeof(WeatherLoggerDbContext))]
    partial class WeatherLoggerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeatherLogger.Domain.Entities.Log.ApiLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ApiLogs");
                });

            modelBuilder.Entity("WeatherLogger.Domain.Entities.User.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("WeatherLogger.Domain.Entities.User.UserCityHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("UserCityHistories");
                });

            modelBuilder.Entity("WeatherLogger.Domain.Entities.Weather.GameCityWeather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageTemperatureCelsius")
                        .HasColumnType("float");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GameCityWeathers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageTemperatureCelsius = 12.0,
                            CityName = "Sarajevo",
                            CountryName = "BA",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3255)
                        },
                        new
                        {
                            Id = 2,
                            AverageTemperatureCelsius = 10.0,
                            CityName = "London",
                            CountryName = "UK",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3317)
                        },
                        new
                        {
                            Id = 3,
                            AverageTemperatureCelsius = 28.0,
                            CityName = "Cairo",
                            CountryName = "EG",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3319)
                        },
                        new
                        {
                            Id = 4,
                            AverageTemperatureCelsius = 4.0,
                            CityName = "Oslo",
                            CountryName = "NO",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3321)
                        },
                        new
                        {
                            Id = 5,
                            AverageTemperatureCelsius = 18.0,
                            CityName = "Madrid",
                            CountryName = "ES",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3323)
                        },
                        new
                        {
                            Id = 6,
                            AverageTemperatureCelsius = 12.0,
                            CityName = "Paris",
                            CountryName = "FR",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3327)
                        },
                        new
                        {
                            Id = 7,
                            AverageTemperatureCelsius = 10.0,
                            CityName = "Berlin",
                            CountryName = "DE",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3329)
                        },
                        new
                        {
                            Id = 8,
                            AverageTemperatureCelsius = 16.0,
                            CityName = "Rome",
                            CountryName = "IT",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3331)
                        },
                        new
                        {
                            Id = 9,
                            AverageTemperatureCelsius = 20.0,
                            CityName = "Athens",
                            CountryName = "GR",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3333)
                        },
                        new
                        {
                            Id = 10,
                            AverageTemperatureCelsius = 5.0,
                            CityName = "Moscow",
                            CountryName = "RU",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3336)
                        },
                        new
                        {
                            Id = 11,
                            AverageTemperatureCelsius = 15.0,
                            CityName = "Tokyo",
                            CountryName = "JP",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3338)
                        },
                        new
                        {
                            Id = 12,
                            AverageTemperatureCelsius = 22.0,
                            CityName = "Sydney",
                            CountryName = "AU",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3340)
                        },
                        new
                        {
                            Id = 13,
                            AverageTemperatureCelsius = 13.0,
                            CityName = "Beijing",
                            CountryName = "CN",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3342)
                        },
                        new
                        {
                            Id = 14,
                            AverageTemperatureCelsius = 12.0,
                            CityName = "New York",
                            CountryName = "US",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3344)
                        },
                        new
                        {
                            Id = 15,
                            AverageTemperatureCelsius = 19.0,
                            CityName = "Los Angeles",
                            CountryName = "US",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3345)
                        },
                        new
                        {
                            Id = 16,
                            AverageTemperatureCelsius = 7.0,
                            CityName = "Toronto",
                            CountryName = "CA",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3347)
                        },
                        new
                        {
                            Id = 17,
                            AverageTemperatureCelsius = 10.0,
                            CityName = "Vancouver",
                            CountryName = "CA",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3349)
                        },
                        new
                        {
                            Id = 18,
                            AverageTemperatureCelsius = 17.0,
                            CityName = "Mexico City",
                            CountryName = "MX",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3352)
                        },
                        new
                        {
                            Id = 19,
                            AverageTemperatureCelsius = 26.0,
                            CityName = "Rio de Janeiro",
                            CountryName = "BR",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3354)
                        },
                        new
                        {
                            Id = 20,
                            AverageTemperatureCelsius = 18.0,
                            CityName = "Buenos Aires",
                            CountryName = "AR",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3356)
                        },
                        new
                        {
                            Id = 21,
                            AverageTemperatureCelsius = 17.0,
                            CityName = "Cape Town",
                            CountryName = "ZA",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3358)
                        },
                        new
                        {
                            Id = 22,
                            AverageTemperatureCelsius = 16.0,
                            CityName = "Johannesburg",
                            CountryName = "ZA",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3359)
                        },
                        new
                        {
                            Id = 23,
                            AverageTemperatureCelsius = 15.0,
                            CityName = "Istanbul",
                            CountryName = "TR",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3361)
                        },
                        new
                        {
                            Id = 24,
                            AverageTemperatureCelsius = 30.0,
                            CityName = "Dubai",
                            CountryName = "AE",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3363)
                        },
                        new
                        {
                            Id = 25,
                            AverageTemperatureCelsius = 28.0,
                            CityName = "Singapore",
                            CountryName = "SG",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3365)
                        },
                        new
                        {
                            Id = 26,
                            AverageTemperatureCelsius = 29.0,
                            CityName = "Bangkok",
                            CountryName = "TH",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3367)
                        },
                        new
                        {
                            Id = 27,
                            AverageTemperatureCelsius = 25.0,
                            CityName = "Delhi",
                            CountryName = "IN",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3369)
                        },
                        new
                        {
                            Id = 28,
                            AverageTemperatureCelsius = 13.0,
                            CityName = "Seoul",
                            CountryName = "KR",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3371)
                        },
                        new
                        {
                            Id = 29,
                            AverageTemperatureCelsius = 3.0,
                            CityName = "Helsinki",
                            CountryName = "FI",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3373)
                        },
                        new
                        {
                            Id = 30,
                            AverageTemperatureCelsius = 5.0,
                            CityName = "Stockholm",
                            CountryName = "SE",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3375)
                        },
                        new
                        {
                            Id = 31,
                            AverageTemperatureCelsius = 8.0,
                            CityName = "Warsaw",
                            CountryName = "PL",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3376)
                        },
                        new
                        {
                            Id = 32,
                            AverageTemperatureCelsius = 16.0,
                            CityName = "Lisbon",
                            CountryName = "PT",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3378)
                        },
                        new
                        {
                            Id = 33,
                            AverageTemperatureCelsius = 11.0,
                            CityName = "Budapest",
                            CountryName = "HU",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3380)
                        },
                        new
                        {
                            Id = 34,
                            AverageTemperatureCelsius = 9.0,
                            CityName = "Prague",
                            CountryName = "CZ",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3383)
                        },
                        new
                        {
                            Id = 35,
                            AverageTemperatureCelsius = 28.0,
                            CityName = "Kuala Lumpur",
                            CountryName = "MY",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3385)
                        },
                        new
                        {
                            Id = 36,
                            AverageTemperatureCelsius = 27.0,
                            CityName = "Lagos",
                            CountryName = "NG",
                            CreatedAt = new DateTime(2026, 1, 31, 14, 14, 12, 462, DateTimeKind.Local).AddTicks(3387)
                        });
                });

            modelBuilder.Entity("WeatherLogger.Domain.Entities.Weather.WeatherRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Humidity")
                        .HasColumnType("int");

                    b.Property<DateTime>("ObservationTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("float");

                    b.Property<string>("WeatherDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("WeatherRecords");
                });

            modelBuilder.Entity("WeatherLogger.Domain.Entities.Weather.WeatherRecordHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ObservationTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("WeatherRecordHistory");
                });

            modelBuilder.Entity("WeatherLogger.Domain.Entities.User.UserCityHistory", b =>
                {
                    b.HasOne("WeatherLogger.Domain.Entities.User.AppUser", "AppUser")
                        .WithMany("CityHistories")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("WeatherLogger.Domain.Entities.User.AppUser", b =>
                {
                    b.Navigation("CityHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
